apiVersion: v1
kind: ReplicationController
metadata:
  name: zipkin-cassandra
spec:
  replicas: 1
  selector:
    app: zipkin-cassandra
  template:
    metadata:
      labels:
        app: zipkin-cassandra
    spec:
      containers:
        - name: cassandra
          image: niccaluim/zipkin-cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
          env:
            - name: CASSANDRA_SERVICE
              value: zipkin-cassandra
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: data
          emptyDir: {}
